-- Generated by scripts/generate-atlas-migration.mjs. Do not change after deployment.
-- IDs refer to the versioned BodyParts3D / Human Atlas manifest shipped with the app.
-- Legacy target_muscles is preserved. Only explicitly reviewed exercise names are assigned.
ALTER TABLE exercises ADD COLUMN atlas_muscles TEXT
  CHECK (atlas_muscles IS NULL OR (json_valid(atlas_muscles) AND json_type(atlas_muscles) = 'object'));

-- トレッドミルウォーキング
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1394","FJ1394M","FJ1397","FJ1397M","FJ1437","FJ1437M","FJ1433","FJ1433M","FJ1441","FJ1441M","FJ1442","FJ1442M","FJ1443","FJ1443M","FJ1418","FJ1418M"],"secondary":["FJ1395","FJ1395M","FJ1435","FJ1435M","FJ1436","FJ1436M","FJ1444","FJ1444M","FJ1419","FJ1419M","FJ1420","FJ1420M","FJ1439","FJ1439M","FJ1422","FJ1422M","FJ1431","FJ1431M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('トレッドミルウォーキング', 'ウォーキング', 'Treadmill walking');

-- ストレッチボード
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1394","FJ1394M","FJ1397","FJ1397M","FJ1437","FJ1437M"],"secondary":[],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('ストレッチボード');

-- バンド肩回し
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1468","FJ1468M","FJ1467","FJ1467M","FJ1513","FJ1513M"],"secondary":["FJ1447","FJ1447M","FJ1464","FJ1464M","FJ1446","FJ1446M","FJ1500","FJ1500M","FJ1504","FJ1504M","FJ1506","FJ1506M","FJ1508","FJ1508M","FJ1520","FJ1520M","FJ1521","FJ1521M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('バンド肩回し');

-- ベンチステップ
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1433","FJ1433M","FJ1441","FJ1441M","FJ1442","FJ1442M","FJ1443","FJ1443M","FJ1418","FJ1418M"],"secondary":["FJ1395","FJ1395M","FJ1435","FJ1435M","FJ1436","FJ1436M","FJ1394","FJ1394M","FJ1397","FJ1397M","FJ1437","FJ1437M","FJ1419","FJ1419M","FJ1420","FJ1420M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('ベンチステップ', 'ステップアップ', 'Step-up');

-- バランスボールスクワット
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1433","FJ1433M","FJ1441","FJ1441M","FJ1442","FJ1442M","FJ1443","FJ1443M","FJ1418","FJ1418M"],"secondary":["FJ1395","FJ1395M","FJ1435","FJ1435M","FJ1436","FJ1436M","FJ1394","FJ1394M","FJ1397","FJ1397M","FJ1437","FJ1437M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('バランスボールスクワット');

-- カーフレイズ
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1394","FJ1394M","FJ1397","FJ1397M","FJ1437","FJ1437M"],"secondary":[],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('カーフレイズ', 'Standing calf raise');

-- カイザーチェストプレス
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1447","FJ1447M","FJ1464","FJ1464M","FJ1446","FJ1446M"],"secondary":["FJ1477","FJ1477M","FJ1479","FJ1479M","FJ1480","FJ1480M","FJ1468","FJ1468M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('カイザーチェストプレス', 'チェストプレス', 'ベンチプレス', 'Bench Press', 'Chest Press');

-- ラットプルダウン
UPDATE exercises SET atlas_muscles = '{"primary":[],"secondary":["FJ1507","FJ1507M","FJ1478","FJ1478M","FJ1512","FJ1512M","FJ1486","FJ1486M","FJ1487","FJ1487M","FJ1520","FJ1520M","FJ1536","FJ1536M","FJ1537","FJ1537M"],"unavailable":["広背筋"]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('ラットプルダウン', 'Lat Pulldown');

-- グッドモーニング
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1395","FJ1395M","FJ1435","FJ1435M","FJ1436","FJ1436M","FJ1418","FJ1418M"],"secondary":["FJ1527","FJ1527M","FJ1528","FJ1528M","FJ1535","FJ1535M","FJ1544","FJ1544M","FJ1403","FJ1403M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('グッドモーニング', 'Good Mornings');

-- アダクター
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1403","FJ1403M","FJ1402","FJ1402M","FJ1401","FJ1401M","FJ1404","FJ1404M"],"secondary":["FJ1421","FJ1421M","FJ1427","FJ1427M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('アダクター', 'ヒップアダクション', 'Hip Adduction');

-- アブダクター
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1419","FJ1419M","FJ1420","FJ1420M"],"secondary":["FJ1438","FJ1438M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('アブダクター', 'ヒップアブダクション', 'Hip Abduction');

-- シーテッドロウ
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1536","FJ1536M","FJ1537","FJ1537M","FJ1554","FJ1554M"],"secondary":["FJ1478","FJ1478M","FJ1512","FJ1512M","FJ1486","FJ1486M","FJ1487","FJ1487M","FJ1513","FJ1513M","FJ1507","FJ1507M","FJ1520","FJ1520M"],"unavailable":["広背筋"]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('シーテッドロウ', 'Seated Row');

-- バタフライ
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1447","FJ1447M","FJ1464","FJ1464M","FJ1446","FJ1446M"],"secondary":["FJ1468","FJ1468M"],"unavailable":[]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('バタフライ', 'ペックデック', 'Pec Deck');

-- レッグレイズ
UPDATE exercises SET atlas_muscles = '{"primary":["FJ1422","FJ1422M","FJ1431","FJ1431M"],"secondary":["FJ1452","FJ1452M","FJ1433","FJ1433M"],"unavailable":["腹直筋"]}'
WHERE atlas_muscles IS NULL AND name COLLATE NOCASE IN ('レッグレイズ', 'Leg Raise');
